### ISSUE TITLE
Add code of conduct page

### ISSUE THREAD

**Issue by acacheung** [dockyard/uxeast#27]
Can be post-launch

**Comment by acacheung** [comment]
Needs @kidfribble to provide copy

**Comment by kidfribble** [comment]
@rgbcolor @atreni I believe you have an edited version of this, or am I wrong?

**Comment by rgbcolor** [comment]
@kidfribble We did not rewrite the code of conduct, only change that you might be thinking about is I suggested we remove "Conference staff can be identified as they'll be wearing branded t-shirts." b/c we do not have staff shirts. 

From what I remember, text is exactly the same as this otherwise. http://confcodeofconduct.com/

**Comment by kidfribble** [comment]
@acacheung can we reuse the content from last years code of conduct but delete the line "Conference staff can be identified as they'll be wearing branded t-shirts."?

**Comment by acacheung** [comment]
yup
